# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('comments', models.CharField(blank=True, max_length=250, null=True)),
                ('applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
